apiVersion: v1
kind: ResourceQuota
metadata:
  name: example-resource-quota
  namespace: dev-environment
spec:
  hard:
    cpu: "2"              # Total CPU requests
    memory: 2Gi           # Total memory requests
    pods: "5"            # Maximum number of pods
    limits.cpu: "2"       # Total CPU limits
    limits.memory: 2Gi    # Total memory limits