---
- name: Example Playbook with Different Variable Data Types
  hosts: localhost
  vars:
    # String Variable
    string_var: "Hello, Ansible!"

    # Numerical Variable
    num_var: 42

    # List Variable
    list_var:
      - item1
      - item2
      - item3

    # Dictionary Variable
    dict_var:
      key1: value1
      key2: value2
      key3: value3

    # Boolean Variable
    bool_var: true

  tasks:
    - name: Display Variables
      debug:
        msg:
          - "String Variable: {{ string_var }}"
          - "Numerical Variable: {{ num_var }}"
          - "List Variable: {{ list_var }}"
          - "Dictionary Variable: {{ dict_var }}"
          - "Boolean Variable: {{ bool_var }}"