apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: busybox
      command: ["sh", "-c", "echo 'Hello Persistent Storage' > /usr/share/busybox/hello.txt && sleep 3600"]
      volumeMounts:
        - mountPath: "/usr/share/busybox"
          name: my-storage
  volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: my-pvc